create table public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null 
    check (type in ('income', 'expense')),
  amount numeric(12, 2) not null 
    check (amount > 0),
  category text not null,
  description text,
  transaction_date date not null default current_date,
  external_message_id text,
  created_at timestamptz not null default now()
);

create index transactions_user_id_idx
on public.transactions(user_id);

create unique index transactions_external_message_id_idx
on public.transactions(external_message_id)
where external_message_id is not null;

alter table public.transactions enable row level security;

create policy "Users can view their own transactions"
on public.transactions
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can create their own transactions"
on public.transactions
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update their own transactions"
on public.transactions
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their own transactions"
on public.transactions
for delete
to authenticated
using (auth.uid() = user_id);